Hexastack/eazychart

packages/ez-react/src/index.ts, packages/ez-react/src/recipes/pie/SemiCircleChart.tsx, packages/ez-vue/index.ts
=> fix: export recipes in ez-vue / ez-react

packages/ez-react/.gitignore, packages/ez-react/.storybook/main.js, packages/ez-react/.storybook/manager-head.html, packages/ez-react/.storybook/manager.js, packages/ez-react/.storybook/theme.js, packages/ez-vue/.gitignore, packages/ez-vue/.storybook/main.js, packages/ez-vue/.storybook/manager-head.html, packages/ez-vue/.storybook/manager.js, packages/ez-vue/.storybook/theme.js
Added Eazychart logo + configured the build for production env.
=> feat: configure storybook theme

CODE_OF_CONDUCT.md, README.md, packages/ez-core/README.md, packages/ez-css/README.md, packages/ez-react/README.md
- Updated the readme file so it would contain proper information
- Added a readme file for each of the packages
- Added a code of conduct for contributors
=> docs: add all readme files + update content

README.md, lerna.json, packages/ez-core/README.md, packages/ez-core/package.json, packages/ez-css/README.md, packages/ez-css/package.json, packages/ez-dev/package.json, packages/ez-react/README.md, packages/ez-react/package.json, packages/ez-vue/README.md, packages/ez-vue/package.json
Fix readme links + update versions.
=> Fix links in Readme file + bump version

README.md, packages/ez-react/package.json, packages/ez-react/yarn.lock, packages/ez-vue/README.md, packages/ez-vue/package.json, packages/ez-vue/yarn.lock, yarn.lock
Set vue as a peer dependencies + remove unused deps.
Fixes #10
=> fix: vue peer dependency + remove unused deps

packages/ez-vue/index.ts
Remove default export in vue
Fixes #15 
=> fix: remove default export in vue

packages/ez-dev/jest/snapshots/recipes/scatter/BubbleChart.spec.tsx.snap, packages/ez-dev/jest/snapshots/recipes/scatter/ScatterChart.spec.tsx.snap, packages/ez-react/tests/unit/recipes/scatter/BubbleChart.spec.tsx, packages/ez-react/tests/unit/recipes/scatter/ScatterChart.spec.tsx, packages/ez-vue/tests/unit/recipes/scatter/BubbleChart.spec.tsx, packages/ez-vue/tests/unit/recipes/scatter/ScatterChart.spec.tsx
=> fix: revert scatter + bubble snapshot unit tests

packages/ez-react/src/components/Chart.tsx, packages/ez-vue/src/components/Chart.tsx
Regarding issue #31
Fixes [#31](https://github.com/Hexastack/eazychart/issues/31)
=> fix: issue#31: checks if the width and height are negative and returns 0 if so, otherwise returns calculated values

packages/ez-vue/tests/unit/recipes/area/AreaChart.spec.tsx, packages/ez-vue/tests/unit/recipes/bar/BarChart.spec.tsx, packages/ez-vue/tests/unit/recipes/column/ColumnChart.spec.tsx, packages/ez-vue/tests/unit/recipes/column/LineColumnChart.spec.tsx, packages/ez-vue/tests/unit/recipes/line/LineChart.spec.tsx, packages/ez-vue/tests/unit/recipes/line/LineErrorMarginChart.spec.tsx, packages/ez-vue/tests/unit/recipes/pie/IrregularPieChart.spec.tsx, packages/ez-vue/tests/unit/recipes/pie/PieChart.spec.tsx, packages/ez-vue/tests/unit/recipes/pie/RadialChart.spec.tsx, packages/ez-vue/tests/unit/recipes/pie/SemiCircleChart.spec.tsx, packages/ez-vue/tests/unit/recipes/scatter/BubbleChart.spec.tsx, packages/ez-vue/tests/unit/recipes/scatter/ScatterChart.spec.tsx
=> fix: issue#1: adds `onResize` missing props to tests with warnings

packages/ez-react/.storybook/docs-root.css, packages/ez-react/.storybook/preview.js, packages/ez-react/src/docs/2_installation.stories.mdx, packages/ez-react/src/docs/3_yourfirstchart.stories.mdx
- Added "Your first chart" section in the documentation.
- Updated "Installation" section in the documentation.
Fixes #46 
=> feat: add your first chart & update installation

README.md, packages/ez-react/README.md, packages/ez-react/src/docs/3_yourfirstchart.stories.mdx, packages/ez-vue/README.md
Update readme files to set new domain key props and minor updates to the storybook dovs.
=> docs: update docs for domain key props

packages/ez-core/src/utils/axis.ts, packages/ez-dev/jest/snapshots/components/scales/GridLines.spec.tsx.snap, packages/ez-react/src/components/scales/grid/GridLines.tsx, packages/ez-react/src/recipes/line/LineChart.stories.tsx, packages/ez-react/src/recipes/scatter/ScatterChart.stories.tsx, packages/ez-react/src/recipes/scatter/ScatterChart.tsx, packages/ez-vue/src/components/scales/grid/GridLines.tsx, packages/ez-vue/src/recipes/scatter/ScatterChart.stories.tsx
This PR fixes the issue about grid lines not being properly rendered.
Fixes #63 
=> fix: grid lines

packages/ez-dev/jest/snapshots/recipes/column/LineColumnChart.spec.tsx.snap, packages/ez-react/src/recipes/column/LineColumnChart.tsx, packages/ez-vue/src/recipes/column/LineColumnChart.tsx
This PR fixes the LineColumnChart to have centred points.
Fixes #43
=> fix: linecolumn chart centred points

.github/ISSUE_TEMPLATE/Bug_report.yml, .github/ISSUE_TEMPLATE/Issue_report.yml
- fix the templates for both issue reporting and bug reporting
=> fix: reporting templates

packages/ez-core/src/sample-data.ts, packages/ez-dev/jest/snapshots/components/shapes/Area.spec.tsx.snap, packages/ez-react/tests/unit/components/shapes/Area.spec.tsx, packages/ez-vue/tests/unit/components/shapes/Area.spec.tsx
This PR adds unit tests for the AreaChart.
Fixes #76
=> feat: added AreaChart unit tests

packages/ez-react/src/index.ts, packages/ez-vue/index.ts
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
=> fix: export ResponsiveChartContainer in Vue & React

packages/ez-react/src/docs/4_1_customCSS.stories.mdx, packages/ez-react/src/docs/4_2_responsiveCharts.stories.mdx, packages/ez-react/src/docs/4_3_commonProps.stories.mdx
This PR will: 
- Add images and gifs links in the storybook docs
- Add code of both React & Vue.
=> fix: add links to images and gifs and add the code in react as well

packages/ez-react/src/recipes/map/BubbleMapChart.tsx
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
=> fix: bubble map layers

packages/ez-react/src/recipes/map/BubbleMapChart.tsx
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
=> feat: add support for layers colors

packages/ez-react/src/components/Map.tsx
Fixes the nested map projection.
=> fix: nested map projection
